### ISSUE TITLE
Rollback Auto Update not compatible with WP 6.6 yet

### ISSUE THREAD

**Issue by BeingFreed** [WordPress/rollback-update-failure#12]
I have the plugin Rollback Auto Update on my site, and it's not yet tested for WordPress 6.6.  Anybody have an idea of when it'll be compatible?

**Comment by afragen** [comment]
The Rollback plugin is specifically set to automatically deactivate in WP 6.6 because it was incorporated into core in WP 6.6. 

In other words, the plugin is not needed for WP 6.6 only for WP 6.5 and lower per the plugin's requirements.

**Comment by BeingFreed** [comment]
Thanks for the clarification.
