### ISSUE TITLE
Suggestion of an alternative: renaming directories instead of zipping

### ISSUE THREAD

**Issue by galbaras** [WordPress/rollback-update-failure#2]
Rather than zipping up the old directory and possibly unzipping it back, why not just rename to `example.old`, and then either delete it on success or rename it back on failure (after removing `example` to remove partial installations)?

This should have a very temporary duplication of disk space utilisation by the plugin, but is a MUCH shorter and safer operation in both directions.

**Comment by afragen** [comment]
`rename` or `move` in WP is not the same as PHP `rename`. WP rename depends upon the file system being used and is primarily a file copy/paste, especially if there is a rename problem.

https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/class-wp-filesystem-direct.php#L329

The current issue is copy/paste and the solution shouldn't be part of the problem. It would be better to comment about ideas on the Make Core post as this repository is about the feature plugin.

**Comment by galbaras** [comment]
The documentation describes `rename()` as a function that renames, even across directories, falling back to `copy()` + `delete()` if it fails. What makes you think it's a copy/paste?

Looking at the `install_package()`, I can see that the logic is very specific about removing the destination before installing, at least in most cases, so I agree about a Trac ticket being better.

See https://core.trac.wordpress.org/ticket/52832

**Comment by afragen** [comment]
The specific failure is in `copy_dir()`

**Comment by galbaras** [comment]
I don't see `copy_dir()` in the code. I just see `copy()`. Anyway, Sergey has merged my ticket with [this one](https://core.trac.wordpress.org/ticket/51857), where the whole thing is discussed as a core modification, and you're in it already.

**Comment by afragen** [comment]
`copy_dir()` is in the plugin/theme updating code.

https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/class-wp-upgrader.php#L595
