### ISSUE TITLE
Updates fail when RUF is active and succeed otherwise

### ISSUE THREAD

**Issue by galbaras** [WordPress/rollback-update-failure#3]
I tried to install a premium plugin called CAOS Super Stealth Upgrade from a zip file on several sites that had Rollback Update Failure installed. All of them failed.

After deactivating RUF, the same installation succeeded.

All the sites already had an older version installed, but InfiniteWP normally handles this when I select the option to overwrite the plugin if it exists.

Installing with "upload plugin" from within WP failed in the same way, but succeeded (with the new warning/selection) when RUF is deactivated.

**Comment by afragen** [comment]
Was there some sort of error notice failure notice? Could you screenshot and post it here?

**Comment by galbaras** [comment]
Alas, no errors :(

Could this be related to the new functionality, which allows overwriting plugins?

**Comment by afragen** [comment]
I'm not certain what it's related to, but I'd like to find out.

Can you describe a test case using a public plugin that can be tested locally?

**Comment by galbaras** [comment]
I can confirm that when trying to install WooCommerce while RUF was active, the installation failed, and succeeded when it was deactivated.

**Comment by afragen** [comment]
Was it already installed? 

How did you install it?

**Comment by galbaras** [comment]
It has been installed, then I renamed the directory and the plugin was deactivated. Then, I used InfiniteWP to install with the "overwrite" flag turned on, which shouldn't have been an issue in this case.

Importantly, I have several sites in the same cPanel account, so if RUF uses directories outside the specific WP installation, this can be a problem.

**Comment by afragen** [comment]
Thanks for the info. It seems there is an issue somewhere with InfiniteWP. I'll see if I can replicate locally.

**Comment by afragen** [comment]
I think I've fixed this. Please update to v0.5.2 and confirm. Thanks.

**Comment by galbaras** [comment]
Seems fixed indeed. I can now update plugins and even upload/overwrite them. Thank you.
