### ISSUE TITLE
Need repository secrets added for GitHub Actions

### ISSUE THREAD

**Issue by afragen** [WordPress/rollback-update-failure#4]
I have added @10up's GitHub Actions for WordPress SVN integration, however, I don't have access to set the repository secrets required.

Could someone add the appropriate `SVN_USERNAME` and `SVN_PASSWORD` secrets so that the GitHub Actions will run?

Thanks.

**Comment by dd32** [comment]
I've added the `SVN_USERNAME` and `SVN_PASSWORD` secrets to this repo for the `githubsync` account and ensured it has the required plugins.svn access.
